@startuml common-flow

"АСУ ТП" as asutp -> MRMS : передача информации\nо выходе параметров\nза допустимые границы
MRMS -> MRMS : генерация задания
"Старший инженер" as senior -> MRMS : назначение\nзадания на инженера
"Инженер" as engineer -> MRMS : взятие задания\nв работу
"Инженер" as engineer -> MRMS : заполнение чек-листа
MRMS -> MRMS : сохранение чек-листа
"Главный инженер" as superviser -> MRMS : просмотр\nзаполнненых чек-листов

@enduml