@startuml user-scenarios
actor "Пользователь" as user

box MRMS
participant "Система авторизации" as auth
participant "Главный экран" as main_screen
participant "Задание на ремонт" as order
participant "Чек-лист" as check_list
end box

group Получения задания на ремонт, сотрудником с ролью инженер
user -> auth : авторизация\nпользователя
auth -> main_screen : открытие списка\nназначенных заданий на ремонт
main_screen -> order : открытие задания\nна ремонт
order -> order : смена состояния\nна "В работе"
order -> check_list : открытие\nчек-листа
check_list -> check_list : заполнение,\n прикрепление медиа файлов
check_list -> check_list : перевод в\nсостояние "Заполнен"
check_list -> order : перевод задания\nв состояние "Выполнено"
order -> main_screen : переход\nна главный экран
end group

group Ручное создание задания на ремонт
user -> auth : авторизация\nпользователя\nс ролью старший инженер
auth -> main_screen : открытие списка\nсозданных заданий на ремонт\nкнопка на создание нового задания,\nкнопка перехода на список\nзаполненных чек-листов
main_screen -> order : создать задание
order -> order : указание оборудования
order -> check_list : задание чек-листа
check_list -> order : возврат к заданию
order -> order : назначение инженера для выполнения
order -> order : перевод в состояние "В работу"
order -> main_screen : переход\nна главный экран
end group

group Указание инженера на задании
user -> auth : авторизация\nпользователя\nс ролью старший инженер
auth -> main_screen : открытие списка\nсозданных заданий на ремонт\nкнопка на создание нового задания,\nкнопка перехода на список\nзаполненных чек-листов
main_screen -> order : выбор задания,\nоткрыть его содержимое
order -> order : выбора инженера\nдля исполнения
order -> order : перевод в состояние "В работу"
order -> main_screen : переход\nна главный экран
end group

group Просмотр чек-листа
user -> auth : авторизация\nпользователя\nс ролью старший инженер/главный инженер
auth -> main_screen : открытие списка\nсозданных заданий на ремонт\nкнопка на создание нового задания,\nкнопка перехода на список\nзаполненных чек-листов
main_screen -> check_list : выбор чек-листа,\nоткрыть его содержимое
check_list -> main_screen : переход\nна главный экран
end group

@enduml